export type Product = {
  id: number;
  slug: string;
  name: string;
  brand: string;
  puffs: number;
  battery: string;
  features: string[];
  colors: string[];
  accent: string;
  shape: "rounded" | "box" | "slim";
  featured: boolean;
  description: string;
};

export const productSeed: Omit<Product, "id">[] = [
  { slug: "turbo-x", name: "Turbo-X", brand: "Rifbar", puffs: 25000, battery: "700 mAh", features: ["Pantalla digital", "Doble modo", "Carga USB-C"], colors: ["Naranja", "Blanco", "Negro"], accent: "#ff5b35", shape: "rounded", featured: true, description: "Potencia ajustable y autonomía para todo el día en un cuerpo compacto con acabado premium." },
  { slug: "fzzybar", name: "Fzzybar", brand: "Fzzy", puffs: 20000, battery: "850 mAh", features: ["Pantalla digital", "Aire ajustable", "Carga rápida"], colors: ["Azul", "Lima"], accent: "#b9e51b", shape: "box", featured: true, description: "Un diseño atrevido con control de aire preciso y lectura clara de batería." },
  { slug: "donet", name: "Donet", brand: "Suonon", puffs: 50000, battery: "900 mAh", features: ["Indicador digital", "Dual Mesh", "Tanque visible"], colors: ["Lavanda", "Rosa"], accent: "#9a7cf1", shape: "rounded", featured: true, description: "Máxima duración, vapor consistente y un diseño suave inspirado en dulces." },
  { slug: "meteor", name: "Meteor", brand: "VOOA", puffs: 70000, battery: "1000 mAh", features: ["Modo ajustable", "Dual Mesh", "Indicador LED"], colors: ["Turquesa", "Negro"], accent: "#12bfa4", shape: "slim", featured: true, description: "Alto rendimiento y control total en un dispositivo delgado con gran autonomía." },
  { slug: "crypto-vibe", name: "Crypto Vibe", brand: "Crypto", puffs: 30000, battery: "850 mAh", features: ["Pantalla digital", "Dual Mesh", "Carga USB-C"], colors: ["Dorado", "Negro"], accent: "#d8ac53", shape: "box", featured: false, description: "Acabado metálico y una experiencia intensa con pantalla de estado integrada." },
  { slug: "air-plus", name: "Air+", brand: "Crave+", puffs: 6500, battery: "650 mAh", features: ["Diseño premium", "Recargable", "Liviano"], colors: ["Uva", "Blanco"], accent: "#8a3c92", shape: "rounded", featured: false, description: "Sencillo, ligero y cómodo. La opción esencial para llevar a cualquier parte." },
  { slug: "dummy-xf", name: "Dummy XF", brand: "Dummy Vapes", puffs: 7500, battery: "650 mAh", features: ["Indicador de líquido", "Quaq Mesh", "Recargable"], colors: ["Mango", "Rosa"], accent: "#ffca20", shape: "slim", featured: false, description: "Colores vibrantes y sabor uniforme con indicador práctico de líquido." },
  { slug: "orionbar", name: "Orionbar", brand: "Lost Vape", puffs: 7500, battery: "650 mAh", features: ["Aire ajustable", "Mesh Coil", "Carga rápida"], colors: ["Azul", "Negro"], accent: "#147bb7", shape: "box", featured: false, description: "Construcción transparente, flujo ajustable y el carácter de Lost Vape." },
  { slug: "heavy-weight", name: "Heavy Weight", brand: "Tyson 2.0", puffs: 7000, battery: "550 mAh", features: ["Material de calidad", "Mesh Coil", "Recargable"], colors: ["Negro", "Verde"], accent: "#78a52f", shape: "rounded", featured: false, description: "Una pieza robusta con textura táctil y rendimiento confiable." },
  { slug: "genius", name: "Genius", brand: "Selected Vibe", puffs: 8000, battery: "800 mAh", features: ["Pantalla digital", "Mesh Coil", "Carga USB-C"], colors: ["Amarillo", "Rojo"], accent: "#ff8a1c", shape: "slim", featured: false, description: "Color degradado, pantalla clara y una experiencia suave de principio a fin." },
  { slug: "geek-us", name: "Geek US", brand: "Geek", puffs: 30000, battery: "800 mAh", features: ["Pantalla digital", "Mesh Coil", "Modo turbo"], colors: ["Naranja", "Negro"], accent: "#ff6b1a", shape: "box", featured: false, description: "Personalidad gráfica y modo turbo para una respuesta más intensa." },
  { slug: "nova-bar", name: "Nova Bar", brand: "Nova", puffs: 35000, battery: "850 mAh", features: ["Pantalla digital", "Doble modo", "Carga USB-C"], colors: ["Rojo", "Negro"], accent: "#e53220", shape: "box", featured: false, description: "Gran capacidad con controles directos y una estética bicolor sobria." },
  { slug: "extre-bar-turbo-x", name: "Turbo-X", brand: "Extre Bar", puffs: 40000, battery: "650 mAh", features: ["Pantalla digital", "Doble modo", "Flujo ajustable"], colors: ["Negro", "Amarillo"], accent: "#f2b928", shape: "box", featured: false, description: "Pantalla curva, doble malla y modos Normal y Turbo con flujo de aire ajustable." },
  { slug: "tasteflex-50k", name: "Tasteflex", brand: "Tasteflex", puffs: 50000, battery: "900 mAh", features: ["Tanque visible", "Doble modo", "Triple Mesh"], colors: ["Negro", "Rosa"], accent: "#e98d78", shape: "slim", featured: false, description: "Gran autonomía, depósito visible y sistema de alimentación asistida para mantener el sabor." },
  { slug: "elux-astra-50k", name: "Astra", brand: "Elux", puffs: 50000, battery: "850 mAh", features: ["Pantalla digital", "Dual Mesh", "Normal y Turbo"], colors: ["Azul", "Transparente"], accent: "#89aef3", shape: "rounded", featured: false, description: "Pantalla amplia, doble malla y dos modos de potencia en un cuerpo compacto." },
  { slug: "glamee-dice-6k", name: "Dice", brand: "Glamee", puffs: 6000, battery: "No confirmada", features: ["Diseño compacto", "Activación por calada", "Formato desechable"], colors: ["Rojo", "Negro"], accent: "#d43a32", shape: "slim", featured: false, description: "Formato estilizado y compacto de 6K, pensado para uso sencillo sin configuraciones." },
  { slug: "glamee-gt-8k", name: "GT", brand: "Glamee", puffs: 8000, battery: "Recargable", features: ["Pantalla digital", "Modo Turbo", "Carga USB-C"], colors: ["Verde", "Negro"], accent: "#22a66f", shape: "box", featured: false, description: "Pantalla informativa y modo Turbo en un dispositivo recargable de 8K." },
  { slug: "glamee-nova-4k", name: "Nova", brand: "Glamee", puffs: 4000, battery: "2200 mAh", features: ["Mesh Coil", "16 ml", "Activación por calada"], colors: ["Blanco", "Dorado"], accent: "#d6a340", shape: "slim", featured: false, description: "Dispositivo de 4K con depósito de 16 ml, batería de alta capacidad y malla integrada." },
  { slug: "glamee-flow-4500", name: "Flow", brand: "Glamee", puffs: 4500, battery: "No confirmada", features: ["Formato compacto", "Activación por calada", "Diseño liviano"], colors: ["Morado", "Dorado"], accent: "#7562c8", shape: "slim", featured: false, description: "Diseño portátil de 4.5K con uso directo y una selección amplia de sabores." },
  { slug: "space-max-bx8000", name: "BX8000", brand: "Space Max", puffs: 8000, battery: "600 mAh", features: ["Pantalla LED", "Mesh Coil", "Carga USB-C"], colors: ["Azul", "Verde"], accent: "#3f70d8", shape: "slim", featured: false, description: "Depósito de 15 ml, batería recargable y pantalla para consultar líquido y carga." },
  { slug: "g-turbo", name: "G-Turbo", brand: "Oxbar", puffs: 36000, battery: "900 mAh", features: ["Pantalla inteligente", "Doble modo", "Aire ajustable"], colors: ["Rosa", "Negro"], accent: "#ef3f79", shape: "rounded", featured: false, description: "Tecnología Oxbar, pantalla inteligente y dos modos de potencia en un acabado llamativo." },
  { slug: "oxbar-g9500", name: "G9500", brand: "Oxbar", puffs: 9500, battery: "650 mAh", features: ["Pantalla inteligente", "Lanyard gratis", "Carga USB-C"], colors: ["Rojo", "Negro"], accent: "#e83d3d", shape: "rounded", featured: false, description: "Formato compacto con pantalla inteligente, batería de 650 mAh y lanyard incluido." },
  { slug: "oxbar-ice-nic", name: "Ice-Nic", brand: "Oxbar", puffs: 35000, battery: "900 mAh", features: ["Pantalla inteligente", "Niveles ajustables", "Carga USB-C"], colors: ["Negro", "Rojo"], accent: "#7e2939", shape: "box", featured: false, description: "Pantalla inteligente y niveles ajustables en un dispositivo de gran capacidad." },
  { slug: "oxbar-dualblend", name: "Dualblend", brand: "Oxbar", puffs: 36000, battery: "900 mAh", features: ["Pantalla inteligente", "Doble sabor", "Carga USB-C"], colors: ["Azul", "Morado"], accent: "#7186d9", shape: "rounded", featured: false, description: "Dos sabores en un dispositivo con pantalla inteligente y batería recargable." },
  { slug: "oxbar-pod-juicy", name: "Pod Juicy", brand: "Oxbar", puffs: 30000, battery: "Recargable", features: ["Pantalla inteligente", "Pod desechable", "Indicador de nivel"], colors: ["Negro", "Dorado"], accent: "#d2b42d", shape: "slim", featured: false, description: "Sistema de pod desechable con batería recargable y pantalla inteligente." },
  { slug: "oxbar-svopp-pod-30k", name: "SVOPP Pod", brand: "Oxbar", puffs: 30000, battery: "Recargable", features: ["Pantalla inteligente", "Pod desechable", "Indicador de nivel"], colors: ["Negro", "Azul"], accent: "#2f9ed8", shape: "slim", featured: false, description: "SVOPP Pod de 30K con batería recargable y pod desechable." },
  { slug: "oxbar-svopp-pod-50k", name: "SVOPP Pod", brand: "Oxbar", puffs: 50000, battery: "Recargable", features: ["Pantalla inteligente", "Pod desechable", "Indicador de nivel"], colors: ["Negro", "Rojo"], accent: "#e74343", shape: "slim", featured: false, description: "Variante SVOPP Pod de 50K para una duración superior." },
  { slug: "lost-mary-mt", name: "MT", brand: "Lost Mary", puffs: 35000, battery: "1000 mAh", features: ["Pantalla inteligente", "Smooth y Turbo", "Carga USB-C"], colors: ["Azul", "Rosa"], accent: "#5ab7ff", shape: "slim", featured: false, description: "Diseño premium, gran autonomía y modos Smooth y Turbo para personalizar la experiencia." },
  { slug: "lost-mary-nera-kit", name: "Nera Kit", brand: "Lost Mary", puffs: 40000, battery: "800 mAh", features: ["Pantalla inteligente", "Diseño transparente", "Base recargable"], colors: ["Transparente", "Negro"], accent: "#9b8b77", shape: "box", featured: false, description: "Kit transparente con pantalla inteligente y batería de 800 mAh." },
  { slug: "lost-mary-nera-pod", name: "Nera Pod", brand: "Lost Mary", puffs: 40000, battery: "800 mAh", features: ["Nivel visible de ml", "Base intercambiable", "Pod transparente"], colors: ["Transparente", "Negro"], accent: "#a99679", shape: "slim", featured: false, description: "Pod transparente con nivel de líquido visible y base intercambiable." },
  { slug: "sp40000", name: "SP40000", brand: "Spaceman", puffs: 40000, battery: "1000 mAh", features: ["Pantalla inteligente", "Alta autonomía", "Carga USB-C"], colors: ["Negro", "Verde"], accent: "#7d9841", shape: "box", featured: false, description: "Potencia y autonomía con pantalla inteligente y batería de 1000 mAh." },
  { slug: "sp50000", name: "SP50000", brand: "Spaceman", puffs: 50000, battery: "1000 mAh", features: ["Pantalla inteligente", "Alta autonomía", "Mesh Coil"], colors: ["Violeta", "Negro"], accent: "#6752d8", shape: "box", featured: true, description: "Máxima duración y respuesta constante con una pantalla de información completa." },
  { slug: "extre-100k", name: "Extre", brand: "Maskking", puffs: 100000, battery: "800 mAh", features: ["Pantalla digital", "Mesh Coil", "Modo boost"], colors: ["Negro", "Naranja"], accent: "#ff6a29", shape: "rounded", featured: true, description: "Capacidad extrema, construcción resistente y tecnología Mesh Coil de alto rendimiento." },
  { slug: "geekbar-ice-prince", name: "Ice Prince", brand: "Geek Bar", puffs: 50000, battery: "800 mAh", features: ["Pantalla inteligente", "Mesh Coil", "Carga USB-C"], colors: ["Naranja", "Negro"], accent: "#ff6a32", shape: "box", featured: false, description: "Tecnología Geek Bar, pantalla inteligente y Mesh Coil en formato de 50K." },
  { slug: "elfbar-ice-king", name: "Ice King", brand: "Elfbar", puffs: 40000, battery: "850 mAh", features: ["Pantalla inteligente", "5 niveles de frío", "Carga USB-C"], colors: ["Blanco", "Morado"], accent: "#9a70d6", shape: "slim", featured: false, description: "Pantalla inteligente y cinco niveles de frío para personalizar cada uso." },
  { slug: "elfbar-duke", name: "Duke", brand: "Elfbar", puffs: 35000, battery: "750 mAh", features: ["Pantalla inteligente", "3 niveles de potencia", "Carga USB-C"], colors: ["Verde", "Negro"], accent: "#78913d", shape: "rounded", featured: false, description: "Tres niveles de potencia, pantalla inteligente y batería de 750 mAh." },
  { slug: "hqd-cuvie-glaze", name: "Cuvie Glaze", brand: "HQD", puffs: 15000, battery: "650 mAh", features: ["Pantalla inteligente", "Dual Mesh Coil", "Carga USB-C"], colors: ["Negro", "Gris"], accent: "#777b7f", shape: "slim", featured: false, description: "Diseño práctico con pantalla inteligente y tecnología Dual Mesh Coil." },
  { slug: "meloso", name: "Meloso", brand: "Geekbar", puffs: 9000, battery: "600 mAh", features: ["Dual Mesh Coil", "Recargable", "Diseño liviano"], colors: ["Amarillo", "Rosa"], accent: "#e6e572", shape: "slim", featured: false, description: "Una opción accesible y ligera con Dual Mesh Coil para un sabor consistente." },
  { slug: "fire-boost", name: "Fire Boost", brand: "Fire Boost", puffs: 12000, battery: "650 mAh", features: ["Pantalla de batería", "Dual Mesh", "Aire ajustable"], colors: ["Rosa", "Verde"], accent: "#df5a9b", shape: "rounded", featured: false, description: "Pantalla práctica, flujo ajustable y buen rendimiento en un formato económico." },
  { slug: "orionbar-budget", name: "Orion Bar", brand: "Lost Vape", puffs: 7500, battery: "650 mAh", features: ["Aire ajustable", "Mesh Coil", "Carga USB-C"], colors: ["Azul", "Negro"], accent: "#147bb7", shape: "box", featured: false, description: "Construcción transparente, malla y flujo de aire regulable." },
  { slug: "spaceman-10k-pro", name: "10K Pro", brand: "Spaceman", puffs: 10000, battery: "800 mAh", features: ["Pantalla inteligente", "Flujo MTL/RDL", "Carga USB-C"], colors: ["Morado", "Negro"], accent: "#7358a9", shape: "box", featured: false, description: "Pantalla de batería y líquido, malla y control de aire MTL/RDL." },
  { slug: "airmez-matrix-25k", name: "Matrix", brand: "Airmez", puffs: 25000, battery: "800 mAh", features: ["Pantalla táctil", "Dos modos", "Dual Mesh"], colors: ["Morado", "Negro"], accent: "#8d6bd1", shape: "rounded", featured: false, description: "Pantalla táctil de gran formato, dos modos y doble malla." },
  { slug: "craftbox-v-play", name: "V-Play", brand: "Craftbox", puffs: 20000, battery: "850 mAh", features: ["Pantalla con juegos", "Aire ajustable", "Dual Mesh"], colors: ["Rosa", "Negro"], accent: "#dc2389", shape: "box", featured: false, description: "Pantalla a color, minijuegos y controles de potencia y aire." },
  { slug: "dragbar-b5000", name: "B5000", brand: "Dragbar", puffs: 5000, battery: "500 mAh", features: ["Mesh Coil", "13 ml", "Carga USB-C"], colors: ["Rosa", "Naranja"], accent: "#f07c83", shape: "rounded", featured: false, description: "Formato sencillo de 5K con depósito de 13 ml y malla." },
  { slug: "friobar-mx-10k", name: "MX 10K", brand: "Friobar", puffs: 10000, battery: "650 mAh", features: ["Pantalla digital", "DUOMESH ajustable", "Aire ajustable"], colors: ["Azul", "Transparente"], accent: "#35aeea", shape: "box", featured: false, description: "Cuerpo transparente con pantalla, flujo regulable y DUOMESH." },
  { slug: "vapmod-all-spark", name: "All Spark", brand: "Vapmod", puffs: 5000, battery: "650 mAh", features: ["Flujo MTL/DTL", "Mesh Coil", "Carga USB-C"], colors: ["Rosa", "Negro"], accent: "#e93a76", shape: "box", featured: false, description: "Control de aire para calada MTL o DTL y resistencia de malla." },
  { slug: "glamee-alien-5k", name: "Alien", brand: "Glamee", puffs: 5000, battery: "2200 mAh", features: ["Mesh Coil", "18 ml", "Activación por calada"], colors: ["Azul", "Negro"], accent: "#357cc6", shape: "slim", featured: false, description: "Batería integrada de alta capacidad, depósito de 18 ml y malla." },
  { slug: "airis-speedy-15k", name: "Speedy", brand: "Airis", puffs: 15000, battery: "650 mAh", features: ["Modos S y D", "Dual Mesh", "USB-C y Lightning"], colors: ["Rojo", "Negro"], accent: "#d83b38", shape: "slim", featured: false, description: "Dos modos, pantalla de estado y doble sistema de carga." },
  { slug: "airis-alpha-touch", name: "Alpha Touch", brand: "Airis", puffs: 20000, battery: "650 mAh", features: ["Pantalla táctil HD", "Tres modos", "Dual Mesh"], colors: ["Rosa", "Negro"], accent: "#e3498f", shape: "rounded", featured: false, description: "Pantalla táctil a color, tres potencias y doble malla." },
  { slug: "true-story-20k", name: "True Story", brand: "True Story", puffs: 20000, battery: "700 mAh", features: ["Tanque transparente", "Tres modos", "Pantalla HD"], colors: ["Rosa", "Negro"], accent: "#da3d68", shape: "rounded", featured: false, description: "Tanque visible, pantalla animada HD y tres modos de uso." },
  { slug: "vookbar-cyber-pro", name: "Cyber Pro", brand: "Vookbar", puffs: 20000, battery: "Recargable", features: ["Pantalla personalizable", "Bluetooth", "Funciones inteligentes"], colors: ["Azul", "Negro"], accent: "#20a7cf", shape: "box", featured: false, description: "Modelo inteligente de 20K con pantalla personalizable y Bluetooth." },
  { slug: "klik-klak-elements", name: "Elements", brand: "Klik Klak", puffs: 5000, battery: "No confirmada", features: ["Sistema magnético", "Sabores combinables", "Formato modular"], colors: ["Rosa", "Negro"], accent: "#d52b75", shape: "rounded", featured: false, description: "Sistema modular magnético para acoplar unidades y combinar sabores." },
  { slug: "lost-angel-50k", name: "Lost Angel 50K", brand: "Lost Angel", puffs: 50000, battery: "1000 mAh", features: ["Pantalla curva", "Dual Mesh", "Normal y Boost"], colors: ["Negro", "Azul"], accent: "#4d75d8", shape: "box", featured: true, description: "Sistema modular de alto rendimiento con pantalla curva y pod intercambiable." },
  { slug: "star-maxus-50k", name: "Star Maxus", brand: "Star Maxus", puffs: 50000, battery: "Recargable", features: ["Pantalla inteligente", "Mesh Coil", "Carga USB-C"], colors: ["Azul", "Negro"], accent: "#426fd1", shape: "rounded", featured: true, description: "Dispositivo de gran capacidad con pantalla de estado y carga USB-C." },
  { slug: "adjust-myrusher-40k", name: "MyRusher", brand: "Adjust", puffs: 40000, battery: "1000 mAh", features: ["Tanque transparente", "Dual Mesh", "3 modos"], colors: ["Rojo", "Negro"], accent: "#df4056", shape: "rounded", featured: true, description: "Tres modos de potencia, flujo ajustable y tanque visible en formato de 40K." },
  { slug: "nexa-ultra-50k", name: "Nexa Ultra", brand: "Nexa", puffs: 50000, battery: "Recargable", features: ["Pantalla inteligente", "Mesh Coil", "Carga USB-C"], colors: ["Morado", "Negro"], accent: "#775bd5", shape: "box", featured: true, description: "Modelo Ultra de 50K con indicadores de estado y batería recargable." },
  { slug: "lady-dinner-galax-60k", name: "Galax", brand: "Lady Dinner", puffs: 60000, battery: "Recargable", features: ["Pantalla inteligente", "Mesh Coil", "Carga USB-C"], colors: ["Rosa", "Negro"], accent: "#dd4f94", shape: "rounded", featured: true, description: "Dispositivo Galax de larga duración con pantalla y tecnología de malla." },
];
